/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AuthenticatorInterface, passThroughInterceptor } from './core';

export * from '@apimatic/oauth-adapters';
export * from '@apimatic/authentication-adapters';
export const customAuthenticationProvider = ({
}: {
}): AuthenticatorInterface<boolean> => {
  return (requiresAuth?: boolean) => {
    if (!requiresAuth) {
      return passThroughInterceptor;
    }
       return (request, options, next) => {
      return next(request, options);
    };
  };
};
